package:
  name: quickfix
  version: "1.15.2"

source:
  git_url: https://github.com/hanlonlab/quickfix.git
  # git_url: https://github.com/quickfix/quickfix.git
  # git_rev: "v1.15.1"

build:
  include_recipe: False

requirements:
  build:
    - openssl
  run:
    - openssl

about:
  home: https://github.com/hanlonlab/quickfix
  # home: https://github.com/quickfix/quickfix
  license_file: LICENSE
